const RepData = [
    {
        "VinNumber": "MLBJB29STTD0094708",
        "dateOfBirth": "05-Oct-1980",
        "dateOfAnniversary": "12-Dec-2008",
        "wifeDOB": "07-04-1985",
        "kid1DOB": "03-08-2017",
        "kid1Gender": "Male",
        "kid2DOB": "",
        "kid2Gender": "",
        "wifeWork": "Teacher",
        "phoneNumber": "9876543210",
        "alternativePhoneNumber": "9123456780",
        "emailId": "nilesh@gmail.com",
        "panNumber": "ABCDE1234F",
        "gstNumber": "27ABCDE1234F1Z5",
        "address": "123 Street, City, State",
        "vehicleNumber": "MH12AB1234",
        "vehicleBrand": "Honda",
        "vehicleModel": "Civic",
        "vehiclePurchaseYear": "2019",
        "whoBuysVehicle": "Self",
        "additionalCarVariant": "ZX CVT",
        "primaryCarUsage": "Personal",
        "hobbies": "Reading, Travel",
        "membershipInClub": "Rotary",
        "beverages": "Coffee",
        "driven": "Yes",
        "modeOfContact": "Phone",
        "timeOfContact": "Morning",
        "about": "Tech enthusiast",
        "remarks": "Good customer",
        "vehicleFinancier": "HDFC Bank",
        "financeExpiryDate": "12-Dec-2025",
        "insuranceCompanyName": "ICICI Lombard",
        "tExpiryDate": "12-Dec-2024",
        "imageName": "profile1.jpg"
      },
      {
        "VinNumber": "MLBJB29STTD0094709",
        "dateOfBirth": "10-Jan-1975",
        "dateOfAnniversary": "14-Feb-2000",
        "wifeDOB": "22-07-1978",
        "kid1DOB": "15-04-2005",
        "kid1Gender": "Female",
        "kid2DOB": "10-08-2009",
        "kid2Gender": "Male",
        "wifeWork": "Engineer",
        "phoneNumber": "9988776655",
        "alternativePhoneNumber": "9111223344",
        "emailId": "seema@gmail.com",
        "panNumber": "XYZAB6789K",
        "gstNumber": "29XYZAB6789K1Z2",
        "address": "456 Avenue, City, State",
        "vehicleNumber": "MH14CD5678",
        "vehicleBrand": "Toyota",
        "vehicleModel": "Innova",
        "vehiclePurchaseYear": "2021",
        "whoBuysVehicle": "Company",
        "additionalCarVariant": "Crysta V",
        "primaryCarUsage": "Business",
        "hobbies": "Golf, Painting",
        "membershipInClub": "Gymkhana",
        "beverages": "Tea",
        "driven": "No",
        "modeOfContact": "Email",
        "timeOfContact": "Evening",
        "about": "Loyal client",
        "remarks": "Follow-up required",
        "vehicleFinancier": "Axis Bank",
        "financeExpiryDate": "01-Jan-2026",
        "insuranceCompanyName": "Bajaj Allianz",
        "tExpiryDate": "01-Jan-2025",
        "imageName": "profile2.jpg"
      },
      {
        "VinNumber": "MLBJB29STTD0094710",
        "dateOfBirth": "20-Jul-1988",
        "dateOfAnniversary": "",
        "wifeDOB": "",
        "kid1DOB": "",
        "kid1Gender": "",
        "kid2DOB": "",
        "kid2Gender": "",
        "wifeWork": "",
        "phoneNumber": "9001234567",
        "alternativePhoneNumber": "9007654321",
        "emailId": "rahul@example.com",
        "panNumber": "GHJKL3456M",
        "gstNumber": "24GHJKL3456M1Z8",
        "address": "789 Lane, City, State",
        "vehicleNumber": "DL8CAF1234",
        "vehicleBrand": "Hyundai",
        "vehicleModel": "i20",
        "vehiclePurchaseYear": "2020",
        "whoBuysVehicle": "Friend",
        "additionalCarVariant": "Sportz",
        "primaryCarUsage": "Personal",
        "hobbies": "Photography",
        "membershipInClub": "NA",
        "beverages": "Juice",
        "driven": "Yes",
        "modeOfContact": "SMS",
        "timeOfContact": "Afternoon",
        "about": "Nature lover",
        "remarks": "New customer",
        "vehicleFinancier": "SBI",
        "financeExpiryDate": "15-Jul-2025",
        "insuranceCompanyName": "Tata AIG",
        "tExpiryDate": "15-Jul-2024",
        "imageName": "profile3.jpg"
      },
      {
        "VinNumber": "MLBJB29STTD0094711",
        "dateOfBirth": "01-Mar-1990",
        "dateOfAnniversary": "01-Jan-2020",
        "wifeDOB": "02-Feb-1992",
        "kid1DOB": "",
        "kid1Gender": "",
        "kid2DOB": "",
        "kid2Gender": "",
        "wifeWork": "Doctor",
        "phoneNumber": "8899001122",
        "alternativePhoneNumber": "8899002211",
        "emailId": "anita@example.com",
        "panNumber": "LMNOP9876Q",
        "gstNumber": "22LMNOP9876Q1Z6",
        "address": "101 Colony, City, State",
        "vehicleNumber": "KA05MK3210",
        "vehicleBrand": "Kia",
        "vehicleModel": "Seltos",
        "vehiclePurchaseYear": "2022",
        "whoBuysVehicle": "Spouse",
        "additionalCarVariant": "HTX+",
        "primaryCarUsage": "Leisure",
        "hobbies": "Cooking, Travel",
        "membershipInClub": "Health Club",
        "beverages": "Green Tea",
        "driven": "No",
        "modeOfContact": "Phone",
        "timeOfContact": "Evening",
        "about": "Frequent buyer",
        "remarks": "Likes new models",
        "vehicleFinancier": "ICICI Bank",
        "financeExpiryDate": "20-Mar-2027",
        "insuranceCompanyName": "New India Assurance",
        "tExpiryDate": "20-Mar-2026",
        "imageName": "profile4.jpg"
      },
      {
        "VinNumber": "MLBJB29STTD0094712",
        "dateOfBirth": "15-May-1982",
        "dateOfAnniversary": "20-Nov-2010",
        "wifeDOB": "10-Jun-1985",
        "kid1DOB": "25-Dec-2012",
        "kid1Gender": "Male",
        "kid2DOB": "30-Jan-2015",
        "kid2Gender": "Female",
        "wifeWork": "Architect",
        "phoneNumber": "7766554433",
        "alternativePhoneNumber": "7766558899",
        "emailId": "rajiv@example.com",
        "panNumber": "QWERT1234R",
        "gstNumber": "33QWERT1234R1Z4",
        "address": "55 Greenpark, City, State",
        "vehicleNumber": "TN10XY6789",
        "vehicleBrand": "Maruti",
        "vehicleModel": "Brezza",
        "vehiclePurchaseYear": "2018",
        "whoBuysVehicle": "Self",
        "additionalCarVariant": "ZDi+",
        "primaryCarUsage": "Commute",
        "hobbies": "Music, Cricket",
        "membershipInClub": "Sports Club",
        "beverages": "Soda",
        "driven": "Yes",
        "modeOfContact": "WhatsApp",
        "timeOfContact": "Morning",
        "about": "Regular visitor",
        "remarks": "Interested in upgrade",
        "vehicleFinancier": "Kotak Mahindra",
        "financeExpiryDate": "01-Sep-2024",
        "insuranceCompanyName": "Reliance General",
        "tExpiryDate": "01-Sep-2023",
        "imageName": "profile5.jpg"
      }
];

module.exports = RepData;
